config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
	get 'events/:id/join' => 'events#join_event', as: :join
	resources :users
	resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	belongs_to :attendee, class_name: "User" 
	belongs_to :attended_event, class_name: "Event"
end

app/models/event.rb
class Event < ApplicationRecord
	has_many :attendances, :foreign_key => "attended_event_id"
	has_many :attendees, through: :attendances
	belongs_to :creator, :class_name => "User"
	validates :date, presence: true

	scope :past, -> { where("date < ?", Date.today) }
	scope :upcoming, -> { where("date >= ?", Date.today) } 
end

app/models/user.rb
class User < ApplicationRecord
	has_many :attendances, :foreign_key => "attendee_id"
	has_many :attended_events, through: :attendances
	has_many :created_events, :foreign_key => "creator_id", :class_name => "Event"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	def login(user)
		session[:user_id] = user.id
	end

	def current_user
		User.find(session[:user_id])
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      flash[:success] = "New event saved!"
      redirect_to user_path(current_user)
    else
      flash[:danger] = "Event did not save. Please try again"
      render :new
    end
  end

  def update
    @event.update_attributes(event_params)
  end

  def edit
    @event = Event.find(params[:id])
  end

  def show
    @event = Event.find(params[:id])
    @attendees = @event.attendees.all
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy
    redirect_to root_path
  end

  def index
    @past = Event.past
    @upcoming = Event.upcoming
  end

  def join_event
    @event = Event.find(params[:id])
    @event.attendances.create!(attendee_id: current_user.id)
    redirect_to event_path(@event)
  end

  private

    def event_params
      params.require(:event).permit(:title, :body, :date, :attendee_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash[:success] = "You've successfully signed up!"
      login(@user)
  		redirect_to user_path(@user)
  	else
  		flash[:danger] = "Your signup was unsuccessful. Please try again."
  		redirect_to root_path
  	end
  end

  def show
  	@user = User.find(params[:id])
    @events = Event.where(creator_id: current_user.id)
  end

  private

  	def user_params
  		params.require(:user).permit(:username)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |f|%>
<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :body %>
<%= f.text_field :body %>

<%= f.label :date %>
<%= f.date_field :date %>

<%= f. submit %>

<% end %>

app/views/events/edit.html.erb
<h1>Event Changes</h1>
<%= render 'form' %>

app/views/events/index.html.erb
<h1>Upcoming Events</h1>

<% @upcoming.each do |event| %>

<h3><%= link_to event.title, event_path(event) %></h3>

<p><%= event.body %></p>
<p><%= event.date %></p>
 
<%= link_to "Join Event", join_path(event) %>
<%= link_to "Delete", event_path(event), method: :delete %>
<hr>
<% end %>

<h1>Past Events</h1>

<% @past.each do |event| %>
<h3><%= link_to event.title, event_path(event) %></h3>

<p><%= event.body %></p>
<p><%= event.date %></p>
 
<%= link_to "Join Event", join_path(event) %>
<%= link_to "Delete", event_path(event), method: :delete %>
<hr>
<% end %>

app/views/events/new.html.erb
<h1>Create an Event</h1>

<%= render 'form' %>

app/views/events/show.html.erb
<h1>Event Show Pages</h1>

<h3><%= @event.title %></h3>

<p><%= @event.creator.username %></p>
<% if @attendees != nil %>	
	<% @attendees.each do |peeps| %>
		<h5>Attendees:</h5>
		<p><%= peeps.username %></p>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "My Profile", user_path(session[:user_id]) %>
    <%= link_to "Events", events_path %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>New User Sign Up</h1>

<%= form_for @user do |f|%>

<%= f.label :username %>
<%= f.text_field :username %>

<%= f.submit "Sign Up" %>

<% end %>

app/views/users/show.html.erb
<h1>User Profile for <%= @user.username %> </h1>

<h3>My Events</h3>

<% @events.each do |event| %>
<h4><%= event.title %></h4>
<p><%= event.body %></p>
<small><%= event.date %></small>
<hr>
<% end %>

<h3>Events I'm Attending</h3>

<% @user.attended_events.each do |event| %>
<h5><%= event.title %></h5>
<p><%= event.body %></p>
<hr>
<% end %>

<%= link_to "New Event", new_event_path %>